/**:
  ros__parameters:
    joint_names: [fr3_finger_joint1, fr3_finger_joint2]
    state_publish_rate: 15          # [Hz] 그리퍼 상태 토픽 발행 속도
    feedback_publish_rate: 30       # [Hz] 액션 피드백 발행 속도
    default_speed: 0.1              # [m/s] 기본 개폐 속도
    default_grasp_epsilon:          # grasp 성공 여부 판정 오차
      inner: 0.005                  # [m]
      outer: 0.005                  # [m]

